import {test,expect} from '@playwright/test';
test('selection, adoption, and persistence across both views',async({page})=>{
 await page.goto('/');
 await expect(page.getByText('Demo · sample bench locations')).toBeVisible();
 await page.screenshot({path:'/tmp/vcp-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'List view',exact:true}).click();
 await page.getByRole('textbox',{name:'Search benches'}).fill('VCP-003');
 await page.getByRole('button',{name:'VCP-003',exact:true}).click();
 await expect(page.locator('.detail')).toContainText('Southwest Playground');
 await page.getByRole('button',{name:'Map view',exact:true}).click();
 await expect(page.locator('.detail')).toContainText('VCP-003');
 await page.getByRole('button',{name:'Adopt this bench'}).click();
 await page.getByLabel('Public display name').fill('The Test Family');
 await page.getByLabel('Email address').fill('test@example.com');
 await page.getByRole('button',{name:'2 years',exact:true}).click();
 await page.getByLabel('Your dedication').fill('For peaceful afternoons.');
 await page.getByRole('checkbox').check();
 await page.getByRole('button',{name:'Confirm demo adoption'}).click();
 await expect(page.getByRole('heading',{name:'Your place in the park.'})).toBeVisible();
 await page.getByRole('button',{name:'See your bench'}).click();
 await expect(page.locator('.detail')).toContainText('The Test Family');
 await page.reload();
 await page.getByRole('button',{name:'List view',exact:true}).click();
 await page.getByRole('textbox',{name:'Search benches'}).fill('VCP-003');
 await expect(page.locator('tbody tr')).toHaveCount(1);
 await expect(page.locator('tbody')).toContainText('The Test Family');
 await expect(page.locator('tbody')).toContainText('2 years');
 await expect(page.locator('tbody').getByRole('button',{name:'Adopt now'})).toHaveCount(0);
});
test('filter empty state and mobile layout',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await page.getByRole('textbox',{name:'Search benches'}).fill('no-such-bench');
 await expect(page.getByText('No benches found')).toBeVisible();
 await page.getByRole('button',{name:'Show all benches'}).click();
 await expect(page.getByText('No benches found')).toHaveCount(0);
 await page.getByRole('button',{name:'Filters',exact:true}).click();
 await page.getByLabel('Park area').selectOption('North Woods');
 await page.getByRole('button',{name:'List view',exact:true}).click();
 await expect(page.locator('tbody tr')).toHaveCount(87);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
});
