import React, {useCallback,useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,ArrowLeft,Map as MapIcon,List,Search,SlidersHorizontal,TreePine,MapPin,Heart,Armchair,X,Check,Leaf,ChevronDown,LoaderCircle} from 'lucide-react';
import ParkMap from './Map';
import {Bench,areas,loadBenches,isAdopted,benchNumber,duration,timeLeft,dateLabel,adoptBench,supabase,sampleInventory} from './data';
import './style.css';
function App(){
 const [benches,setBenches]=useState<Bench[]>([]),[view,setView]=useState<'map'|'list'>('map'),[selected,setSelected]=useState<Bench|null>(null),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[area,setArea]=useState('all'),[filters,setFilters]=useState(false),[adopting,setAdopting]=useState<Bench|null>(null),[info,setInfo]=useState<string|null>(null),[success,setSuccess]=useState<Bench|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{try{setBenches(await loadBenches());setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load benches. Please try again.');}finally{setLoading(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(refresh,30000);window.addEventListener('storage',refresh);return()=>{clearInterval(timer);window.removeEventListener('storage',refresh);};},[refresh]);
 const select=useCallback((b:Bench)=>setSelected(b),[]);const startAdoption=useCallback((b:Bench)=>{setAdopting(b);setSelected(b);},[]);
 const filtered=useMemo(()=>benches.filter(b=>(status==='all'||(status==='available'?!isAdopted(b):isAdopted(b)))&&(area==='all'||b.area===area)&&`${benchNumber(b.id)} ${b.area} ${isAdopted(b)?b.donor:''}`.toLowerCase().includes(query.toLowerCase())),[benches,status,area,query]);
 const current=benches.find(b=>b.id===selected?.id)||null;
 useEffect(()=>{if(view==='list'&&selected)requestAnimationFrame(()=>document.getElementById(`bench-${selected.id}`)?.scrollIntoView({block:'center',behavior:'smooth'}));},[view,selected]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'){setInfo(null);setAdopting(null);setSuccess(null);setSelected(null);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
 useEffect(()=>{if(!info&&!adopting&&!success)return;const previous=document.activeElement as HTMLElement|null;const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';const trap=(event:KeyboardEvent)=>{if(event.key!=='Tab')return;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');const nodes=dialog?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input,select,textarea,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&(document.activeElement===first||!dialog?.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&(document.activeElement===last||!dialog?.contains(document.activeElement))){event.preventDefault();first.focus();}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=oldOverflow;document.removeEventListener('keydown',trap);previous?.focus();};},[info,adopting,success]);
 const available=benches.filter(b=>!isAdopted(b)).length;
 return <><header><a className="brand" href="./" aria-label="Van Cortlandt Park home"><span className="brand-icon"><TreePine size={27}/></span><span>VAN CORTLANDT PARK<small>A place for all of us.</small></span></a><nav><button className="nav-active" onClick={()=>{setAdopting(null);setInfo(null);}}>Explore benches</button><button onClick={()=>setInfo('How it works')}>How it works</button><button onClick={()=>setInfo('About the park')}>About the park <ArrowUpRight size={13}/></button></nav><button className="header-cta" onClick={()=>{setStatus('available');document.getElementById('explorer')?.scrollIntoView({behavior:'smooth'});}}>Give a place to pause <ArrowUpRight size={15}/></button></header>
 <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> THE BENCH ADOPTION PROGRAM</div><h1>A little seat.<br/>A lasting <em>connection.</em></h1><p>A favorite view. A familiar path. A moment of quiet.<br className="desktop"/> Adopt a bench and become part of Van Cortlandt Park’s story.</p><div className="hero-meta"><span><MapPin size={14}/> The Bronx, New York</span><i/><span>1,146 acres of possibility</span></div></div><div className="hero-photo"><img src="/woodland.jpg" alt="Sunlight falling through a peaceful green woodland"/><div className="photo-shade"/><div className="photo-caption"><span>A PLACE TO REMEMBER.</span><p>A place to belong.</p></div><span className="photo-badge"><Leaf size={14}/> Rooted in community</span></div></section>
 <section className="explorer" id="explorer"><div className="explorer-heading"><div><div className="eyebrow">FIND YOUR SPECIAL SPOT</div><h2>Every bench has a story.<br className="mobile"/> Start yours.</h2></div><div className="stats"><div><strong>{benches.length || '—'}</strong><span>benches in the park</span></div><div><strong><i className="status-dot available"/>{loading?'—':available}</strong><span>waiting for a story</span></div><div><strong><i className="status-dot adopted"/>{loading?'—':benches.length-available}</strong><span>already loved</span></div></div></div>
 <div className="toolbar"><div className="view-switch"><button className={view==='map'?'active':''} onClick={()=>setView('map')}><MapIcon size={16}/>Map view</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={17}/>List view</button></div><div className="search"><Search size={17}/><input aria-label="Search benches" placeholder="Search bench number, name, or location" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={14}/></button>}</div><label className="status-select"><span className="sr-only">Bench status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All benches</option><option value="available">Available</option><option value="adopted">Adopted</option></select><ChevronDown size={14}/></label><button className={`filter-button ${filters?'active':''}`} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/>Filters{area!=='all'&&<span className="live-dot"/>}</button></div>
 {filters&&<div className="filter-panel"><label>Park area <select value={area} onChange={e=>setArea(e.target.value)}><option value="all">All areas</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label><button onClick={()=>{setArea('all');setStatus('all');setQuery('');}}>Reset filters</button></div>}
 {error?<div className="empty"><h3>We couldn’t load the benches.</h3><p>{error}</p><button className="primary" onClick={refresh}>Try again</button></div>:loading?<div className="empty"><LoaderCircle className="spin"/><p>Finding your place in the park…</p></div>:<div className={`explorer-content ${current?'has-selection':''}`}>
 {view==='map'?<ParkMap benches={filtered} selected={current} onSelect={select} onAdopt={startAdoption}/>:<div className="table-scroll"><table><thead><tr><th>BENCH / LOCATION</th><th>STATUS</th><th>ADOPTED BY</th><th>DURATION</th><th>TIME REMAINING</th><th/></tr></thead><tbody>{filtered.map(b=><tr id={`bench-${b.id}`} key={b.id} className={current?.id===b.id?'selected-row':''} onClick={()=>setSelected(b)}><td><button className="bench-link" onClick={()=>setSelected(b)}>{benchNumber(b.id)}</button><small>{b.area}</small></td><td><Status bench={b}/></td><td>{isAdopted(b)?b.donor:<span className="muted">Your story could go here</span>}</td><td>{isAdopted(b)?duration(b):'—'}</td><td>{timeLeft(b)}</td><td>{!isAdopted(b)&&<button className="text-button" onClick={e=>{e.stopPropagation();startAdoption(b);}}>Adopt now <ArrowUpRight size={14}/></button>}</td></tr>)}</tbody></table></div>}
 {current&&<aside className="detail"><button className="close" aria-label="Close bench details" onClick={()=>setSelected(null)}><X size={19}/></button><div className="bench-art"><Armchair size={52} strokeWidth={1}/><span>A PLACE TO PAUSE</span></div><Status bench={current}/><h3>{benchNumber(current.id)}</h3><p className="location"><MapPin size={14}/>{current.area}</p>{isAdopted(current)?<><label>LOVINGLY ADOPTED BY</label><h4>{current.donor}</h4>{current.dedication&&<blockquote>“{current.dedication}”</blockquote>}<div className="date-details"><span>Adoption term<strong>{duration(current)}</strong></span><span>From<strong>{dateLabel(current.starts)}</strong></span><span>Until<strong>{dateLabel(current.ends)}</strong></span></div></>:<><p className="detail-copy">Make this little corner of the park part of your story. Honor someone special, celebrate a memory, or simply give back.</p><button className="primary" onClick={()=>startAdoption(current)}>Adopt this bench <ArrowRight size={16}/></button><small className="under-button">A meaningful connection starts here.</small></>}</aside>}
 {!filtered.length&&<div className="no-results"><Search size={24}/><h3>No benches found</h3><p>Try another search or reset your filters.</p><button className="primary" onClick={()=>{setQuery('');setStatus('all');setArea('all');}}>Show all benches</button></div>}</div>}
 <div className="explorer-foot"><span>Showing <b>{filtered.length}</b> of {benches.length} benches <span className="foot-divider">·</span> {view==='map'?'Select a bench to discover its story':'Select a row to discover its story'}</span><span><span className="live-dot"/>{supabase?(sampleInventory?'Supabase connected · sample bench locations':'Connected to park records'):'Demo · sample bench locations'}</span></div></section>
 <section className="bottom-callout"><div className="heart-circle"><Heart size={22} strokeWidth={1.4}/></div><div><h3>More than a bench. A gift to your park.</h3><p>Help keep Van Cortlandt Park a welcoming place for generations to come.</p></div><button onClick={()=>setInfo('How it works')}>Learn about the program <ArrowUpRight size={16}/></button></section></main><footer><span><TreePine size={17}/> VAN CORTLANDT PARK</span><p>A little care goes a long way.</p><small>Made for our park. And everyone in it.</small></footer>
 {adopting&&<AdoptionPage bench={adopting} onClose={()=>setAdopting(null)} onComplete={async()=>{await refresh();setSuccess(adopting);setAdopting(null);}}/>}
 {info&&<div className="modal-backdrop" onClick={()=>setInfo(null)}><section className="info-modal" role="dialog" aria-modal="true" aria-label={info} onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close" onClick={()=>setInfo(null)} autoFocus><X/></button><TreePine size={32}/><h2>{info}</h2>{info==='How it works'?<><p>Give a favorite place in the park a story of its own.</p><ol><li><strong>Find your bench.</strong> Explore the map or list and choose a green, available bench.</li><li><strong>Make it yours.</strong> Add your display name, contact email, and a dedication. Choose a 6-month, 1-year, 2-year, or 5-year term.</li><li><strong>Enjoy the connection.</strong> Your adoption appears in both views for the duration you choose. No payment is collected here.</li></ol>{sampleInventory&&<p className="notice">Bench locations and initial adoptions are sample data, not official park records. {supabase?'Adoptions are saved to the shared database.':'Adoptions are saved only in this browser.'}</p>}</>:<><p>Van Cortlandt Park is a green retreat in the Bronx, with woodlands, trails, open fields, and places to pause.</p><p>This bench explorer helps neighbors find a place to celebrate a loved one or make a new memory.</p><a className="text-button" href="https://www.nycgovparks.org/parks/VanCortlandtPark" target="_blank" rel="noreferrer">Visit the official park website <ArrowUpRight size={16}/></a></>}</section></div>}
 {success&&<div className="modal-backdrop"><section className="info-modal success" role="dialog" aria-modal="true" aria-label="Adoption complete"><div className="success-icon"><Check size={28}/></div><div className="eyebrow">A NEW CHAPTER BEGINS</div><h2>Your place in the park.</h2><p>{benchNumber(success.id)} now has a new story. Thank you for giving a place to pause.</p>{sampleInventory&&<p className="notice">{supabase?'Adoption saved to the shared database.':'Demo adoption saved in this browser.'} This sample bench is not an official park reservation.</p>}<button autoFocus className="primary" onClick={()=>{setSelected(success);setSuccess(null);setStatus('all');setQuery('');setArea('all');}}>See your bench <ArrowRight size={16}/></button></section></div>}
 </>;
}
function Status({bench}:{bench:Bench}){const adopted=isAdopted(bench);return <span className={`status-badge ${adopted?'red':'green'}`}><i className={`status-dot ${adopted?'adopted':'available'}`}/>{adopted?'Adopted':'Available'}</span>;}
function AdoptionPage({bench,onClose,onComplete}:{bench:Bench;onClose:()=>void;onComplete:()=>Promise<void>}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[months,setMonths]=useState(12);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);setError('');try{await adoptBench(bench,{name:String(data.get('name')).trim(),email:String(data.get('email')).trim(),months,dedication:String(data.get('dedication')).trim()});await onComplete();}catch(e){setError(e instanceof Error?e.message:'Could not save your adoption. Please try again.');setBusy(false);}}
 return <div className="adoption-page" role="dialog" aria-modal="true" aria-label="Adopt a bench"><div className="adoption-inner"><button className="back-button" disabled={busy} onClick={onClose}><ArrowLeft size={17}/>Back to the park</button><div className="eyebrow">MAKE A LASTING CONNECTION</div><h1>A place for <em>your story.</em></h1><p className="form-intro">A small gesture. A special place. A memory that stays.</p><div className="adoption-layout"><form onSubmit={submit}><h3>Your adoption</h3><label>Public display name <span>*</span><input name="name" required maxLength={100} autoFocus placeholder="e.g. The Rivera Family" pattern=".*\S.*"/><small>This name will appear on the map and in the bench list.</small></label><label>Email address <span>*</span><input name="email" type="email" required maxLength={254} placeholder="you@example.com"/><small>Your email is private and never displayed publicly.</small></label><label>Adoption duration <span>*</span><div className="duration-options">{[6,12,24,60].map(m=><button type="button" key={m} aria-pressed={months===m} className={months===m?'chosen':''} onClick={()=>setMonths(m)}>{m<12?'6 months':`${m/12} year${m>12?'s':''}`}</button>)}</div></label><label>Your dedication <span className="muted">(optional)</span><textarea name="dedication" rows={3} maxLength={240} placeholder="In celebration of someone, something, or a moment that matters."/><small>Up to 240 characters. Visible on your bench’s detail card.</small></label><label className="checkbox"><input type="checkbox" required/>I understand that my display name and dedication will be public.{sampleInventory&&' This uses sample bench data, not an official reservation.'}</label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy} type="submit">{busy?<><LoaderCircle size={17} className="spin"/>Saving your adoption…</>:<>Confirm {supabase?'':'demo '}adoption <ArrowRight size={17}/></>}</button><p className="form-note">No payment required. Your term starts today.</p></form><aside className="adoption-summary"><div className="bench-art"><Armchair size={70} strokeWidth={1}/><span>YOUR LITTLE CORNER OF THE PARK</span></div><Status bench={bench}/><h2>{benchNumber(bench.id)}</h2><p className="location"><MapPin size={15}/>{bench.area}</p><hr/><p>“Sometimes, the most meaningful thing you can give is a place to simply be.”</p>{sampleInventory&&<div className="notice">Sample bench location. {supabase?'Your adoption will be saved to the shared database.':'Your adoption will be saved on this device.'}</div>}</aside></div></div></div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
