import { useEffect, useRef } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { LocateFixed, Plus, Minus } from 'lucide-react';
import { Bench, benchNumber, isAdopted } from './data';
export default function ParkMap({benches,selected,onSelect,onAdopt}:{benches:Bench[];selected:Bench|null;onSelect:(b:Bench)=>void;onAdopt:(b:Bench)=>void}) {
 const container=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null);
 useEffect(()=>{ if(!container.current)return;const m=L.map(container.current,{zoomControl:false,minZoom:12,maxZoom:19,zoomSnap:.25}).fitBounds([[40.8825,-73.903],[40.911,-73.874]],{padding:[25,25]});map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>',maxZoom:19}).addTo(m);layer.current=L.layerGroup().addTo(m);const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(container.current);return()=>{observer.disconnect();m.remove();};},[]);
 useEffect(()=>{if(!layer.current)return;layer.current.clearLayers();benches.forEach(b=>{const adopted=isAdopted(b);const marker=L.circleMarker([b.lat,b.lng],{radius:selected?.id===b.id?8:4.5,color:'#fff',weight:1.5,fillColor:adopted?'#bf6b60':'#44815a',fillOpacity:1});const tip=document.createElement('div');tip.className='bench-tooltip';const title=document.createElement('strong');title.textContent=benchNumber(b.id);tip.append(title);const status=document.createElement('span');status.textContent=adopted?`Adopted by ${b.donor}`:'Available for adoption';tip.append(status);if(!adopted){const button=document.createElement('button');button.textContent='Adopt now →';button.onclick=e=>{e.stopPropagation();onAdopt(b);};tip.append(button);}marker.bindTooltip(tip,{direction:'top',interactive:true,opacity:1});marker.on('click',()=>onSelect(b));marker.addTo(layer.current!);});},[benches,selected,onSelect,onAdopt]);
 useEffect(()=>{if(selected)map.current?.flyTo([selected.lat,selected.lng],16,{duration:.7});},[selected]);
 return <div className="map-shell"><div className="map-canvas" ref={container} aria-label="Interactive map of benches in Van Cortlandt Park"/><div className="map-location"><span className="live-dot"/> VAN CORTLANDT PARK <span className="location-divider"/> Bronx, New York</div><div className="map-controls"><button aria-label="Zoom in" onClick={()=>map.current?.zoomIn()}><Plus size={18}/></button><button aria-label="Zoom out" onClick={()=>map.current?.zoomOut()}><Minus size={18}/></button><button aria-label="Show entire park" onClick={()=>map.current?.flyToBounds([[40.8825,-73.903],[40.911,-73.874]],{padding:[25,25]})}><LocateFixed size={18}/></button></div><div className="map-legend"><span><i className="status-dot available"/>Available</span><span><i className="status-dot adopted"/>Adopted</span></div><div className="map-hint">A little dot. A lasting difference.</div></div>;
}
